# Generated by Django 3.2.3 on 2021-05-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='greeting_1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='home',
            name='greeting_2',
            field=models.CharField(max_length=25),
        ),
    ]
